data <- read.csv("C:/Users/yashv/Downloads/data stats/all_fuels_data.csv")
head(data)
str(data)
data$commodity <- as.factor(data$commodity)
library(dplyr)
average_close <- data %>%
  group_by(commodity) %>%
  summarise(average_close = mean(close, na.rm = TRUE))
  print(average_close)
anova_avg_close <- aov(average_close ~ commodity, data = average_close)
summary(anova_avg_close)
plot(anova_avg_close, which = 2)
if (!require("car")) install.packages("car")
library(car)
levene_test_result <- leveneTest(average_close ~ commodity, data = average_close)
print(levene_test_result)
qqnorm(residuals(anova_avg_close))
qqline(residuals(anova_avg_close), col = "red")
summary(anova_avg_close)